name: CI Process
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  behave-testing:
    #Setup of simple OS of choice. i.e. Linux
    #create VM with ubuntu OS
    runs-on: ubuntu-latest

    permissions:
      issues: write
      checks: write
      pull-requests: write  
      
    steps:
      #Setup of environment for test
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List repo
        run: |
          ls

      #Setup tools necessary for testing, search from marketplace
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'

      #Install behave
      - name: install pip
        run: |
          python -m pip install --upgrade pip
          pip install behave

      #Setup commands for test, junit-> test for individual components
      - name: run bahave test
        run: |
          behave features/ --junit --junit-directory=test-results

          
      - name: upload test results
        if: always()  # executes regardless of the outcome
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

      #marketplace Publish Test Result
      #The combination ** (to handle recursive directories) and * (to handle files in those directories)
      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            test-results/**/*.xml
            #test-results/*.xml
            
      - name: Create an issue
        if: failure()
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: |
            [${{ github.workflow }}] failed during [${{ github.event_name }}]
          assignees: ${{ github.actor }},${{ github.triggering_actor }}
          body: |
            ## Failure Report:
            
            > [!IMPORTANT]
            > Details on failed run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
            - Author: @${{ github.triggering_actor }}
            - Branch: `${{ github.ref }}`
            - Commit: ${{ github.sha }}
            - Workflow Path: `${{ github.workflow_ref }}`
    
            - [ ] **Task**: Review failed run, fix the issue(s), and re-run until successful.
    
            > This issue was created automatically by GitHub, 
            > through `dacbd/create-issue-action@main` action
            > and KemingHe's contribution.
            > **DO NOT** close this issue until resolved.

# Week13 - Step 6b: Send Telegram Message on failure 
      - name: Send Telegram Message on Test Failure(s)
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="Review failed run, fix the issue(s), and re-run until successful."  
          
